BUNDLE_NAME = magnifyprefs
magnifyprefs_FILES = MagRootListController.m
magnifyprefs_FRAMEWORKS = UIKit
magnifyprefs_PRIVATE_FRAMEWORKS = Preferences
magnifyprefs_INSTALL_PATH = /Library/PreferenceBundles
magnifyprefs_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk